### ISSUE TITLE
WoW Error when adding existing File

### ISSUE THREAD

**Issue by Kallar12** [wowdev/TACT.Net#9]
So I was trying to overwrite a file in the intetrface. I have a working cdn without canges but once I add a file it errors out. File was taken from the cdn and was not modified to ensure its not a error with the edit. It gets the correct Filedata to replace.

Heres my code:

![image code](https://i.gyazo.com/2fbf78cdc0b738e4f1ac39eb128afab4.png)

And here is the error:

![image error](https://i.gyazo.com/16542bb50920ebe742d34cf2e7916930.png)

**Comment by barncastle** [comment]
I've just fixed a few minor things, notably 14714a204c6c0274ffb28a6ca90a4346c8301b43 which may or may not be the issue here. Let me know if it was.

I need to download a CDN and client again to test this all properly which I'll do at the weekend if I get the chance.

**Comment by MaxtorCoder** [comment]
Why update the Install file tho. You have to update root, encoding and add an index file which has the supposed edited file in there. And then you would get an  `archive-group` mismatch which is what I am stuck on now.

**Comment by Kallar12** [comment]
Installfile was more of a "it does not work so lets also add it there" idea.

**Comment by Kallar12** [comment]
Error persists
![image error2](https://i.gyazo.com/11a16a7d9590b695b89fdc773e315a11.png)

**Comment by MaxtorCoder** [comment]
Which game version? 😄

**Comment by Kallar12** [comment]
7.3.5.26972

**Comment by barncastle** [comment]
@Kallar12 just a quick update - I have figured a solution to this but it is a lot of finicky code (plus a few fixes). I'll ping you and/or Max at the weekend to get your thoughts on the best way to implement these changes.

**Comment by MaxtorCoder** [comment]
Sure, working on 8.2 anyways.

**Comment by Kallar12** [comment]
Small update. Here my code with changes from recent commit and a exception:

![img error3](https://i.gyazo.com/40126a14cc23f3ceedc509aef20c4490.png)

**Comment by MaxtorCoder** [comment]
I think something is wrong with the reading of the Encoding/Root handler.

**Comment by barncastle** [comment]
The original issue was that old Encoding entries weren't being deleted and the client was throwing an exception because `SUM(CKeyEntries.EKeyCount) != EKeyEntries.Count`. TACT.Net now also throws on this if the Ckeys and Ekeys don't have a 1:1 relationship.

To make things worse, the old TACT.Net build deleted old systemfiles once `Save` was called so my first thought is that you might need to grab the old system files again - sorry about this, the latest build now never deletes any files.

I've tried and tested this on 8.2 and have successfully switched out the login screen model, there's an example in the tests although it is 99% the same as your code.

Also FYI work had a major catastrophe a week back and I've been working overtime trying to rectify the issue hence not having looked into this fully - apologies.

**Comment by MaxtorCoder** [comment]
Wait.. You tested on 8.2? I cannot make 8.2 work with CASCHost.

**Comment by Kallar12** [comment]
So to fix this I just get a new fresh cdn and try again?
Will do that shortly.

**Comment by MaxtorCoder** [comment]
I'll see if I can switch from CASCHost to TACT.Net, just have to add locale support so it can be used by Firestorm.

**Comment by Kallar12** [comment]
Have tested it. Worked for me. :) 
Thanks for the great work. If I find anything else I let you know.
If you need testers or anything else let me know.

@MaxtorCoder Have tried finding you on discord. Can we talk about some things related 8.2? 
My discord is Kallar#7754
